let artistStore = [
  {
    fullname: "Ameen Abdulla",
    email: "ameen@example.com",
    location: "Kerala",
    bio: "Energetic speaker and dancer with 5+ years on stage inspiring youth and entertaining crowds.",
    categories: ["Speaker", "Dancer"],
    languages: ["Malayalam", "English"],
    feeRange: "₹4,000 - ₹8,000",
    agree: true,
  },
  {
    fullname: "Riya Kapoor",
    email: "riya.kapoor@example.com",
    location: "Mumbai",
    bio: "Classical and Bollywood fusion singer performing at weddings and corporate events across India.",
    categories: ["Singer"],
    languages: ["Hindi", "English"],
    feeRange: ">₹8,000 or above",
    agree: true,
  },
  {
    fullname: "Arjun Mehta",
    email: "arjun.dj@example.com",
    location: "Delhi",
    bio: "Professional DJ spinning the best of EDM and Desi beats for over 6 years.",
    categories: ["DJ"],
    languages: ["Hindi", "English"],
    feeRange: ">₹8,000 or above",
    agree: true,
  },
  {
    fullname: "Sneha Sharma",
    email: "sneha.speaker@example.com",
    location: "Bangalore",
    bio: "Motivational speaker empowering students and professionals through impactful talks.",
    categories: ["Speaker"],
    languages: ["English"],
    feeRange: "₹4,000 - ₹8,000",
    agree: true,
  },
  {
    fullname: "Rahul Nair",
    email: "rahul.nair@example.com",
    location: "Chennai",
    bio: "South Indian classical dancer blending tradition with contemporary choreography.",
    categories: ["Dancer"],
    languages: ["Tamil", "Malayalam", "English"],
    feeRange: "Upto ₹4,000",
    agree: true,
  },
  {
    fullname: "Tanya Verma",
    email: "tanya.v@example.com",
    location: "Kolkata",
    bio: "Award-winning playback singer known for soulful and romantic numbers.",
    categories: ["Singer"],
    languages: ["Bengali", "Hindi"],
    feeRange: ">₹8,000 or above",
    agree: true,
  },
  {
    fullname: "Dev Patel",
    email: "djdev@example.com",
    location: "Pune",
    bio: "Club DJ and music producer known for house and trance remixes.",
    categories: ["DJ"],
    languages: ["English", "Hindi"],
    feeRange: "₹4,000 - ₹8,000",
    agree: true,
  },
  {
    fullname: "Kavya Krishnan",
    email: "kavya.dance@example.com",
    location: "Hyderabad",
    bio: "Dynamic Bharatanatyam dancer and cultural performer for stage festivals.",
    categories: ["Dancer"],
    languages: ["Telugu", "Tamil", "English"],
    feeRange: "Upto ₹4,000",
    agree: true,
  },
  {
    fullname: "Nikhil Jain",
    email: "nikhil.speaker@example.com",
    location: "Ahmedabad",
    bio: "Corporate trainer and keynote speaker focusing on leadership and team growth.",
    categories: ["Speaker"],
    languages: ["Hindi", "English"],
    feeRange: ">₹8,000 or above",
    agree: true,
  },
  {
    fullname: "Ishita Roy",
    email: "ishita.music@example.com",
    location: "Jaipur",
    bio: "Versatile singer with a love for retro and indie folk music.",
    categories: ["Singer"],
    languages: ["Hindi", "English", "Bengali"],
    feeRange: "₹4,000 - ₹8,000",
    agree: true,
  },
  {
    fullname: "Manav Singh",
    email: "manav.dj@example.com",
    location: "Ludhiana",
    bio: "Wedding and party DJ with a crowd-pleasing playlist and high energy sets.",
    categories: ["DJ"],
    languages: ["Punjabi", "Hindi", "English"],
    feeRange: "₹4,000 - ₹8,000",
    agree: true,
  },
  {
    fullname: "Sana Ali",
    email: "sana.speaker@example.com",
    location: "Lucknow",
    bio: "TEDx speaker and youth activist delivering talks on social change.",
    categories: ["Speaker"],
    languages: ["Hindi", "English"],
    feeRange: "Upto ₹4,000",
    agree: true,
  },
  {
    fullname: "Zoya Shaikh",
    email: "zoya.dance@example.com",
    location: "Bhopal",
    bio: "Contemporary and freestyle dancer performing at events and competitions nationwide.",
    categories: ["Dancer"],
    languages: ["Hindi", "English"],
    feeRange: "₹4,000 - ₹8,000",
    agree: true,
  },
  {
    fullname: "Ankit Rana",
    email: "ankit.music@example.com",
    location: "Dehradun",
    bio: "Live acoustic performer for cafés, weddings, and college festivals.",
    categories: ["Singer"],
    languages: ["Hindi", "English"],
    feeRange: "Upto ₹4,000",
    agree: true,
  },
  {
    fullname: "Priya Menon",
    email: "priya.art@example.com",
    location: "Trivandrum",
    bio: "Creative dance choreographer and performer blending tradition and innovation.",
    categories: ["Dancer"],
    languages: ["Malayalam", "English"],
    feeRange: "₹4,000 - ₹8,000",
    agree: true,
  },
]


export async function GET() {
  return Response.json(artistStore);
}

export async function POST(request) {
  const newArtist = await request.json();
  artistStore.push(newArtist);
  return Response.json({ message: "Artist added", data: newArtist }, { status: 201 });
}
